# Run Loki as a one replica
deploymentMode: SingleBinary

singleBinary:
  replicas: 1

loki:
  auth_enabled: false
  commonConfig:
    replication_factor: 1
  storage:
    type: filesystem
  schemaConfig:
    configs:
      - from: "2024-04-01"
        store: tsdb
        object_store: filesystem
        schema: v13
        index:
          prefix: loki_index_
          period: 24h
  persistence:
    enabled: true
    accessModes:
      - ReadWriteOnce
    size: 0.3Gi

chunksCache:
  allocatedMemory: 128Mi

resultsCache:
  allocatedMemory: 128Mi

serviceMonitor:
  enabled: true

monitoring:
  selfMonitoring:
    enabled: true
    grafanaAgent:
      install: true

# Zero out replica counts of other deployment modes
backend:
  replicas: 0
read:
  replicas: 0
write:
  replicas: 0

ingester:
  replicas: 0
querier:
  replicas: 0
queryFrontend:
  replicas: 0
queryScheduler:
  replicas: 0
distributor:
  replicas: 0
compactor:
  replicas: 0
indexGateway:
  replicas: 0
bloomCompactor:
  replicas: 0
bloomGateway:
  replicas: 0