apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: frontend
  namespace: monitoring
  labels:
    release: kps
spec:
  namespaceSelector:
    matchNames: ["default"]
  selector:
    matchLabels:
      app: python-guestbook
      tier: frontend
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
